Add libmpbase.so through RM6785-vendor.mk
To avoid conflicts with faceunlock repo
error: vendor/realme/RM6785: MODULE.TARGET.SHARED_LIBRARIES.libmpbase
already defined by external/faceunlock.

Signed-off-by: ImFlynnn <ahmadzaid13.az@gmail.com>